name: Deployment Workflow

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
            
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 6
          run_install: true

      - name: Install dependencies
        working-directory: ./Sprint 2/soen341-rentalapp
        run: pnpm install

      - name: Build Next.js app
        working-directory: ./Sprint 2/soen341-rentalapp
        run: pnpm run build

      - name: Run tests
        working-directory: ./Sprint 2/soen341-rentalapp
        run: pnpm run test

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
