name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./Sprint 2/soen341-rentalapp
        run: npm install

      - name: Build Next.js app
        working-directory: ./Sprint 2/soen341-rentalapp
        run: npm run build

      - name: Run tests
        working-directory: ./Sprint 2/soen341-rentalapp
        run: npm run test
